steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build -t northamerica-south1-docker.pkg.dev/tienda-microservicios-454219/image-registry/orders-microservice -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL=$$DATABASE_URL .
  secretEnv: ['DATABASE_URL']

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'northamerica-south1-docker.pkg.dev/tienda-microservicios-454219/image-registry/orders-microservice',
    ]

availableSecrets:
  secretManager:
  - versionName: projects/591743474309/secrets/ORDERS_DATABASE_URL/versions/1
    env: 'DATABASE_URL'
    

options:
  logging: CLOUD_LOGGING_ONLY